version: "3"
services:
  app:
    image: nginx:1.15-alpine
    container_name: nginx_test
    hostname: nginx_test
    ports:
      - 1811:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./dist/ng-seed:/usr/share/nginx/html/ng-seed
      - ./dist/log:/var/log/nginx
    restart: unless-stopped
networks:
  default:
    external:
      name: compose
